name: LAB4 SapXep

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: 'URL of the input file'
        required: true
        default: 'https://example.com/input.txt'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt g++
      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Show hardware info
        run: |
          echo "=== CPU Info ==="
          cat /proc/cpuinfo | grep "model name" | head -n 1  # Tên CPU
          echo "Number of CPUs: $(nproc)"  # Số lõi CPU
          echo
          echo "=== Memory Info ==="
          free -h  # Thông tin RAM
          echo
          echo "=== Disk Info ==="
          df -h  # Thông tin ổ cứng
      # Bước 3: Tải tệp đầu vào lớn từ URL bên ngoài
      - name: Download input file
        run: |
          wget -O test.txt "${{ github.event.inputs.input_url }}"
      # Bước 4: Biên dịch chương trình C++
      - name: Compile C++ program
        run: g++ -o main main.cpp

      # Bước 5: Chạy chương trình
      - name: Run C++ program
        run: ./main

      # Bước 5.1: In kết quả ra
      - name: In ket qua
        run: cat output.txt
